services:
  - type: web
    name: backend-travel-rtp
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npx knex migrate:latest && node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 6543
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
